### ISSUE TITLE
Wagtail 2.13

### ISSUE THREAD

**Issue by aliceni** [squareweave/wagtailcolumnblocks#8]
The package is incompatible with the Wagtail 2.13 or above.
I used the example codes from README.

- If I upload an image in the first row and then click "CHOOSE AN IMAGE" in the second row, the image in the first row will disappear:
![image](https://user-images.githubusercontent.com/41408550/121336805-72778680-c94e-11eb-9708-004520cd80dc.png)
![image](https://user-images.githubusercontent.com/41408550/121337503-2f69e300-c94f-11eb-9d7f-e033973054d5.png)

- If I skip upload image in the first row but directly click "CHOOSE AN IMAGE" in the second row, the image chooser will not display.

Hope this problem can be fixed ASAP!

**Comment by aliceni** [comment]
can anyone help?

**Comment by Fcog** [comment]
hi, it's been a while and there's no fix for the newest Wagtail version. :(

**Comment by tay-solis** [comment]
Is anyone also having issues publishing the page, or is it just the admin view?

**Comment by Fcog** [comment]
the issue is the admin view where there are no columns anymore

**Comment by stefan-squareweave** [comment]
There is a PR on this repo which claim to make this package work with newer versions. The current iteration of the PR apparently breaks the API however.

Just a note for users of this package, Squareweave doesn't really use this package much and so keeping it up to date is not likely to happen very quickly. If you need to have this work in newer versions of Wagtail in the short term I suggest maintaining your own fork and using something like `-e git+https://github.com/my-username/wagtailcolumnblocks.git@master#egg=wagtailcolumnblocks` in your requirements.txt or equivalent.

**Comment by aliceni81** [comment]
@stefan-squareweave Its been a few months. May I know if you have any plans to release a new package with this problem fixed soon?

**Comment by stefan-squareweave** [comment]
@aliceni81 I can't guarantee it unfortunately. I will try and get some time to test, merge, and publish the PR I mentioned previously in the next couple of weeks, but that may not happen. This would address the 2.13 breakage, but not any similar problems in the future. As mentioned above, maintaining this package is no longer a priority for Squareweave as we really don't use it much. The project we do use it on only updates Wagtail when forced to by security issues.

If you'd like to wait and see if I get a chance to do the work that's OK. Otherwise I would suggest maintaining your own fork as mentioned above. Or, if you and/or somebody else would like to make an official fork with faster update cycles you should feel free to do so. I don't think I'm comfortable making somebody else a maintainer of this repo or the Pypi package due to the possibility of a supply chain attack on the current userbase (this package probably doesn't have a lot of users, but still). If you'd like to go down the replacement fork route, you could register a new name like 'wagtailcolumnblocks-ng' on Pypi and maintain that.

Incidentally I'm also finishing up at Squareweave in the next few weeks (I've been working here for 7+ years!), so this Github account I'm using will stop being used then.

**Comment by stefan-squareweave** [comment]
OK, I got some time today to test the PR and update Pypi. Version 2.3.1 should work with Wagtail >= 2.10 .

The above discussion of Squareweave's priorities is still relevant however. If somebody finds this comment in the future and isn't having much luck getting the package updated, the above suggestions are probably the best bet.
